### ISSUE TITLE
Y.Text not handled

### ISSUE THREAD

**Issue by arolson101** [nikgraf/react-yjs#8]
I see in #1 that you discussed `Y.Text`, but v2.0.0 only handles `Y.XmlText`

**Comment by nikgraf** [comment]
oh, seems like we forgot about it. Can you create PR and add it? It's only about to types or is there a bug?

**Comment by joulev** [comment]
It is indeed only about types, thankfully. I will create a PR for this.

**Comment by nikgraf** [comment]
fixed and release 2.0.1 :)
thanks @joulev & @arolson101
